// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1K338aUuzwfSCcj0Hjail78_QP7yM5k',
    appId: '1:709968555565:web:1e84d09e51c5f6901e52a4',
    messagingSenderId: '709968555565',
    projectId: 'upskillfinder-a10bd',
    authDomain: 'upskillfinder-a10bd.firebaseapp.com',
    storageBucket: 'upskillfinder-a10bd.appspot.com',
    measurementId: 'G-LPK87KLSLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl68WaCSg4lU8o6WIs1J_5yqNwSuRSee8',
    appId: '1:709968555565:android:2af0f75a09d87c9c1e52a4',
    messagingSenderId: '709968555565',
    projectId: 'upskillfinder-a10bd',
    storageBucket: 'upskillfinder-a10bd.appspot.com',
  );
}
